# Generated by Django 6.0 on 2025-12-13 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=20)),
                ('pan_no', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_ac_no', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_code', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('station', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('party_type', models.CharField(choices=[('Mill', 'Mill'), ('Trader', 'Trader'), ('Ginner', 'Ginner')], max_length=20)),
                ('contact_person', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ac_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BargainEntry',
            fields=[
                ('deal_no', models.AutoField(primary_key=True, serialize=False)),
                ('bargain_date', models.DateField()),
                ('station', models.CharField(max_length=100)),
                ('bales', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_condition', models.IntegerField(help_text='Number of Days')),
                ('payment_by', models.CharField(max_length=50)),
                ('delivery_terms', models.CharField(max_length=255)),
                ('deal_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.partymaster')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.partymaster')),
            ],
        ),
        migrations.CreateModel(
            name='PassingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_no', models.CharField(max_length=50)),
                ('approval_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('lot_no', models.CharField(max_length=50)),
                ('approved_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bargain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bargainentry')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('truck_no', models.CharField(max_length=20)),
                ('transport_name', models.CharField(max_length=100)),
                ('quantity_bales', models.IntegerField()),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotton_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('passing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.passingentry')),
            ],
        ),
    ]
