# Generated by Django 6.0.6 on 2026-06-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmmaster',
            name='letterhead',
            field=models.ImageField(blank=True, null=True, upload_to='letterheads/'),
        ),
    ]
