# Generated by Django 6.0 on 2025-12-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymaster',
            name='ho_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partymaster',
            name='party_type',
            field=models.CharField(choices=[('Mill', 'Mill'), ('Trader', 'Trader'), ('Ginner', 'Ginner'), ('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Other', 'Other')], max_length=20),
        ),
    ]
