# Generated by Django 6.0.6 on 2026-07-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmmaster',
            name='branch_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firmmaster',
            name='contact_person_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
