# Generated by Django 6.0.6 on 2026-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_brokeragebill_amount_paid_brokeragebill_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymaster',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
