# Generated by Django 6.0 on 2025-12-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_firmmaster_branch_firmmaster_cin_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargainentry',
            name='advised_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bargainentry',
            name='cash_disc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bargainentry',
            name='cotton_certificate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bargainentry',
            name='delivery_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bargainentry',
            name='quality_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bargainentry',
            name='weight_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bargainentry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
