# Generated by Django 6.0.6 on 2026-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_firmmaster_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymaster',
            name='contact_person_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
