# Generated by Django 6.0.6 on 2026-06-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_partymaster_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bargainentry',
            name='bargain_type',
        ),
        migrations.RemoveField(
            model_name='deliverydetails',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='passingentry',
            name='passing_no',
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='lr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passingentry',
            name='pr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
