# Generated by Django 6.0.6 on 2026-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_bargainentry_bargain_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
