# Generated by Django 6.0.6 on 2026-07-07 08:45

import django.db.models.deletion
from django.db import migrations, models


def create_default_subscriptions(apps, schema_editor):
    Tenant = apps.get_model('api', 'Tenant')
    TenantSubscription = apps.get_model('api', 'TenantSubscription')
    from django.utils import timezone
    from datetime import timedelta
    
    for tenant in Tenant.objects.all():
        if not TenantSubscription.objects.filter(tenant=tenant).exists():
            TenantSubscription.objects.create(
                tenant=tenant,
                plan_type='1_YEAR',
                end_date=timezone.now() + timedelta(days=365),
                is_active=True
            )

def reverse_default_subscriptions(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('1_YEAR', '1 Year Plan'), ('3_YEAR', '3 Year Plan'), ('5_YEAR', '5 Year Plan')], default='1_YEAR', max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.tenant')),
            ],
        ),
        migrations.RunPython(create_default_subscriptions, reverse_default_subscriptions),
    ]
