# Generated by Django 6.0.6 on 2026-06-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_deliverydetails_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bargainentry',
            name='bargain_no_manual',
        ),
        migrations.RemoveField(
            model_name='bargainentry',
            name='qc_buyer',
        ),
        migrations.RemoveField(
            model_name='bargainentry',
            name='qc_seller',
        ),
        migrations.AddField(
            model_name='bargainentry',
            name='quality_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passingentry',
            name='book_bargain_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
