# Generated by Django 6.0.6 on 2026-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='base_firm_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='plan_type',
            field=models.CharField(choices=[('TRIAL', '14-Day Free Trial'), ('1_YEAR', '1 Year Plan'), ('3_YEAR', '3 Year Plan'), ('5_YEAR', '5 Year Plan')], default='1_YEAR', max_length=50),
        ),
    ]
