# Generated by Django 6.0.6 on 2026-06-25 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_bargainentry_bargain_no_manual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassingSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bales', models.IntegerField()),
                ('passing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='api.passingentry')),
            ],
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='passing_split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.passingsplit'),
        ),
    ]
