# Generated by Django 6.0.6 on 2026-07-11 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tenantsubscription_base_firm_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetails',
            name='passing_split',
        ),
        migrations.CreateModel(
            name='BargainSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bales', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending Passing', 'Pending Passing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending Passing', max_length=50)),
                ('bargain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='api.bargainentry')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PassingSplit',
        ),
    ]
