# Generated by Django 6.0.6 on 2026-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_deliverydetails_passing_split_bargainsplit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passingentry',
            name='bales',
            field=models.IntegerField(default=0),
        ),
    ]
