# Generated by Django 6.0.6 on 2026-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_passingentry_bales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymaster',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
