# Generated by Django 6.0.6 on 2026-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_partymaster_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmmaster',
            name='jurisdiction',
            field=models.CharField(blank=True, help_text='e.g. Indore', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firmmaster',
            name='tagline',
            field=models.CharField(blank=True, help_text='e.g. Cotton Broker & Commission Agent', max_length=255, null=True),
        ),
    ]
