# Generated by Django 6.0.6 on 2026-07-28 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_firmmaster_jurisdiction_firmmaster_tagline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bargainentry',
            options={'verbose_name': 'Bargain', 'verbose_name_plural': 'Bargains'},
        ),
        migrations.AlterModelOptions(
            name='brokeragebill',
            options={'verbose_name': 'Brokerage Bill', 'verbose_name_plural': 'Brokerage Bills'},
        ),
        migrations.AlterModelOptions(
            name='deliverydetails',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='partypaymentreceipt',
            options={'verbose_name': 'Payment Receipt', 'verbose_name_plural': 'Payment Receipts'},
        ),
        migrations.AlterModelOptions(
            name='passingentry',
            options={'verbose_name': 'Passing', 'verbose_name_plural': 'Passings'},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'verbose_name': 'Payment Allocation', 'verbose_name_plural': 'Payment Allocations'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Firm', 'verbose_name_plural': 'Firms'},
        ),
        migrations.RenameModel(
            old_name='TenantSubscription',
            new_name='UserSubscription',
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'User Subscription', 'verbose_name_plural': 'User Subscriptions'},
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_subscription', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
