# Generated by Django 6.0.6 on 2026-07-28 07:28

from django.db import migrations


def migrate_subscription_tenant_to_user(apps, schema_editor):
    UserSubscription = apps.get_model('api', 'UserSubscription')
    CustomUser = apps.get_model('api', 'CustomUser')
    
    for sub in UserSubscription.objects.all():
        if sub.tenant:
            user = CustomUser.objects.filter(tenant=sub.tenant).first()
            if user:
                sub.user = user
                sub.save()

def reverse_migration(apps, schema_editor):
    UserSubscription = apps.get_model('api', 'UserSubscription')
    for sub in UserSubscription.objects.all():
        if sub.user and sub.user.tenant:
            sub.tenant = sub.user.tenant
            sub.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_bargainentry_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_subscription_tenant_to_user, reverse_migration)
    ]
