# Generated by Django 6.0.6 on 2026-07-28 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_migrate_subscription_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
