# Generated by Django 6.0.6 on 2026-07-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_usersubscription_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='dodo_customer_id',
        ),
    ]
