# Generated by Django 6.0.6 on 2026-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_brokernote_checklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargainentry',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
