# Generated by Django 6.0.6 on 2026-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_bargainentry_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargainentry',
            name='deal_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bargainentry',
            name='delivery_terms',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bargainentry',
            name='delivery_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bargainentry',
            name='payment_by',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bargainentry',
            name='payment_condition',
            field=models.IntegerField(blank=True, help_text='Days', null=True),
        ),
        migrations.AlterField(
            model_name='bargainentry',
            name='weight_terms',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
