# Generated by Django 6.0.6 on 2026-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_bargainentry_deal_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bargainentry',
            options={'ordering': ['-deal_no'], 'verbose_name': 'Bargain', 'verbose_name_plural': 'Bargains'},
        ),
        migrations.AlterModelOptions(
            name='deliverydetails',
            options={'ordering': ['-id'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='passingentry',
            options={'ordering': ['-id'], 'verbose_name': 'Passing', 'verbose_name_plural': 'Passings'},
        ),
        migrations.AddField(
            model_name='firmmaster',
            name='letterhead_data',
            field=models.TextField(blank=True, help_text='Base64 encoded image data for permanent storage across deployments', null=True),
        ),
    ]
