# Generated by Django 6.0.6 on 2026-10-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_bargainentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmmaster',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
