"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--)sh1-k87x)bm5vi)z7#fy*my0gczt9=!87bzjn$1+x%r8#$9-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',   # For APIs
    'rest_framework_simplejwt', # For JWT Auth
    'corsheaders',      # For connecting to Next.js
    'api',              # Your Cotton Logic
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # For CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.SubscriptionEnforcerMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'api.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS CONFIGURATION
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.1.11:3000",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://192\.168\..*",
]
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.CustomCookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/minute',
    }
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_COOKIE': 'access_token',  # Cookie name
    'AUTH_COOKIE_SECURE': False,    # Set to True in production with HTTPS
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_PATH': '/',
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

UNFOLD = {
    "SITE_TITLE": "CottBook Master Admin",
    "SITE_HEADER": "CottBook Master Admin",
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": ("User Activities"),
                "separator": True,
                "items": [
                    {
                        "title": ("Bargains"),
                        "icon": "shopping_cart",
                        "link": "/admin/api/bargainentry/",
                    },
                    {
                        "title": ("Passings"),
                        "icon": "fact_check",
                        "link": "/admin/api/passingentry/",
                    },
                    {
                        "title": ("Deliveries"),
                        "icon": "local_shipping",
                        "link": "/admin/api/deliverydetails/",
                    },
                    {
                        "title": ("Brokerage Invoices"),
                        "icon": "receipt_long",
                        "link": "/admin/api/brokeragebill/",
                    },
                    {
                        "title": ("Payment Receipts"),
                        "icon": "payments",
                        "link": "/admin/api/partypaymentreceipt/",
                    },
                    {
                        "title": ("Payment Allocations"),
                        "icon": "account_balance_wallet",
                        "link": "/admin/api/paymentallocation/",
                    },
                ],
            },
            {
                "title": ("Master Data"),
                "separator": True,
                "items": [
                    {
                        "title": ("Broker Firms"),
                        "icon": "business",
                        "link": "/admin/api/firmmaster/",
                    },
                    {
                        "title": ("Client Parties"),
                        "icon": "groups",
                        "link": "/admin/api/partymaster/",
                    },
                ]
            },
            {
                "title": ("Platform Admin"),
                "separator": True,
                "items": [
                    {
                        "title": ("Registered Firms (Tenants)"),
                        "icon": "domain",
                        "link": "/admin/api/tenant/",
                    },
                    {
                        "title": ("Firm Subscriptions"),
                        "icon": "card_membership",
                        "link": "/admin/api/tenantsubscription/",
                    },
                    {
                        "title": ("Users"),
                        "icon": "person",
                        "link": "/admin/api/customuser/",
                    },
                ]
            }
        ]
    }
}